# fly.toml app configuration file generated for teams10 on 2025-04-16T18:07:06+05:45
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'teams10'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
